### ISSUE TITLE
Cleanup of cleanup()

### ISSUE THREAD

**Issue by MGlauser** [ArtskydJ/create-temp-file#13]
If cleanup is called on a non-existent temp file from a stream, an error is emitted, which calls cleanup.  Infinite loop.  This seems best place to fix it.  Just checks for existence of file first.

``` js
writeStream.cleanup = function cln(cb) {
  writeStream.end()
  fs.access(path, fs.W_OK, function(err) {
    if (!err) {
      //console.log("Cleaning up: " + path);
      fs.unlink(path, function(err) {
        if (err) writeStream.emit('error', err)
        if (cb) cb(err)
      });
    } else {
      //console.log("Skipping cleanup.");
    }
  });
}
```

**Comment by ArtskydJ** [comment]
I presume you have code that resembles this:

``` js
writeStream.on('error', function (err) {
    writeStream.cleanup()
})
```

The problem with checking if the file exists, like you suggest, is that you can run into race conditions where the file is found to exist, then is deleted asynchronously by outside code, and then is attempted to be deleted by `cleanup`.

One way to avoid the race condition is to have `cleanup` look like this:

``` js
writeStream.cleanup = function cln(cb) {
    writeStream.end()
    fs.unlink(path, function(err) {
        if (err && err.code !== 'ENOENT') writeStream.emit('error', err)
        if (cb) cb(err)
    })
}
```

But this infinite loop is caused by outside code. (And perhaps an imperfect abstraction?)

A way to avoid the infinite loop is to write your code like so:

``` js
writeStream.on('error', function (err) {
    if (err.code !== 'ENOENT') { // Avoid infinite loops
        writeStream.cleanup()
    }
})
```

At this time I plan to continue having this module emit an `error` event for `ENOENT`.

**Comment by MGlauser** [comment]
Thank you kindly for your response and consideration.
I’ll take this to the source of the problem as you suggest.

Michael Glauser.
