### ISSUE TITLE
through instead of stream

### ISSUE THREAD

**Issue by Kikobeats** [ArtskydJ/create-temp-file#4]
I love this idea, but instead of require Stream for node use wrappers like through that return you a stream object based in your version of node and make your library compatible with all version of node.

https://www.npmjs.com/package/through2

**Comment by ArtskydJ** [comment]
I don't require stream in this module; in [index.js](https://github.com/ArtskydJ/create-temp-file/blob/master/index.js) I am using `fs.createWriteStream()` which has been around since [node v0.2](https://nodejs.org/docs/v0.2.0/api.html#fs-writestream-154).

Are you saying this...

``` js
var writeStream = fs.createWriteStream(path).pipe(through2()) // line 7
// ...
return writeStream // line 15
```

...would improve compatibility?

Am I missing something?

**Comment by Kikobeats** [comment]
ops, really not need it. through2 is more when you need implement something that follow a stream interface, so sorry :)

**Comment by ArtskydJ** [comment]
No problem. :grinning:
